# Generated by Django 4.1.2 on 2022-10-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.TextField()),
                ('Nomorhp', models.CharField(max_length=20)),
                ('Email', models.TextField()),
                ('Pekerjaan', models.TextField()),
                ('Domisili', models.TextField()),
            ],
        ),
    ]
